"""
Host-only automatic hardware keystroke typer for Windows.

This program does not open network connections and does not use Power Automate.
It intentionally supports only characters that can be generated by a US/ANSI
physical keyboard. Unsupported characters are rejected before any text is sent.
"""

from __future__ import annotations

import ctypes
from ctypes import wintypes
from collections.abc import Callable
import json
import os
import queue
import random
import re
import socket
import struct
import subprocess
import sys
import threading
import time
import tkinter as tk
import traceback
import winreg
from pathlib import Path
from tkinter import filedialog, messagebox, ttk


# Three human-like timing profiles. Every delay is sampled independently.
TIMING_PRESETS = {
    "very_fast": {
        "label": "极速",
        "character": (35, 85),
        "key_down": (18, 38),
        "shift": (20, 42),
        "space": (30, 75),
        "punctuation": (90, 210),
        "newline": (180, 380),
    },
    "fast": {
        "label": "快速",
        "character": (90, 190),
        "key_down": (28, 52),
        "shift": (30, 58),
        "space": (70, 145),
        "punctuation": (180, 360),
        "newline": (320, 650),
    },
    "natural": {
        "label": "自然",
        "character": (225, 455),
        "key_down": (38, 72),
        "shift": (42, 86),
        "space": (150, 310),
        "punctuation": (480, 920),
        "newline": (720, 1350),
    },
    "slow": {
        "label": "慢速",
        "character": (480, 820),
        "key_down": (55, 105),
        "shift": (65, 125),
        "space": (300, 560),
        "punctuation": (850, 1450),
        "newline": (1200, 2100),
    },
    "very_slow": {
        "label": "很慢",
        "character": (850, 1450),
        "key_down": (70, 135),
        "shift": (85, 165),
        "space": (520, 950),
        "punctuation": (1300, 2300),
        "newline": (1900, 3300),
    },
    "ultra_slow": {
        "label": "超慢",
        "character": (1500, 2800),
        "key_down": (90, 180),
        "shift": (110, 220),
        "space": (900, 1700),
        "punctuation": (2200, 4000),
        "newline": (3200, 5500),
    },
}
timing_preset_name = "fast"
auto_trigger_window_seconds = 7.0
focus_wait_seconds = 4.0
enter_wait_seconds = 4.0

SETTINGS_DIRECTORY_NAME = "CloudHardwareTypist"
SETTINGS_FILE_NAME = "settings.json"


# Windows constants.
CF_UNICODETEXT = 13
GMEM_MOVEABLE = 0x0002
INPUT_KEYBOARD = 1
KEYEVENTF_KEYUP = 0x0002
KEYEVENTF_SCANCODE = 0x0008
MAPVK_VSC_TO_VK_EX = 3
VK_F8 = 0x77
VK_F9 = 0x78
VK_F10 = 0x79
VK_CONTROL = 0x11
VK_MENU = 0x12
VK_V = 0x56
VK_LCONTROL = 0xA2
VK_RCONTROL = 0xA3
DOUBLE_CTRL_WINDOW_SECONDS = 0.65
WH_KEYBOARD_LL = 13
HC_ACTION = 0
WM_INPUT = 0x00FF
WM_KEYDOWN = 0x0100
WM_KEYUP = 0x0101
WM_SYSKEYDOWN = 0x0104
WM_SYSKEYUP = 0x0105
RID_INPUT = 0x10000003
RIM_TYPEKEYBOARD = 1
RIDEV_INPUTSINK = 0x00000100
PM_REMOVE = 0x0001
HWND_MESSAGE = -3
PROCESS_QUERY_LIMITED_INFORMATION = 0x1000
WUYING_FOREGROUND_PROCESSES = {"wuying.exe", "stream_viewer.exe"}
VM_FOREGROUND_PROCESSES = {
    # VMware Workstation / Player
    "vmware.exe", "vmplayer.exe",
    # Oracle VirtualBox
    "virtualboxvm.exe",
    # Hyper-V VMConnect
    "vmconnect.exe",
    # QEMU and common SPICE viewers
    "qemu-system-x86_64.exe", "qemu-system-i386.exe",
    "virt-viewer.exe", "remote-viewer.exe",
}
DEFAULT_TARGET_LABEL = "云电脑 / 虚拟机控制台（自动识别）"
VMWARE_TARGET_LABEL = "VMware Workstation（vmware.exe / vmplayer.exe）"
DEFAULT_TARGET_PROCESSES = WUYING_FOREGROUND_PROCESSES | VM_FOREGROUND_PROCESSES
target_process_names = set(DEFAULT_TARGET_PROCESSES)
target_application_label = DEFAULT_TARGET_LABEL
target_window_handle: int | None = None
application_window_handles: dict[str, int] = {}
ERROR_ALREADY_EXISTS = 183
MUTEX_NAME = "Local\\CloudHardwareTypist-8DDA2254-3A4E-4C74-91A0-FB0D74F21F26"
WINDOW_TITLE = "云端逐键输入助手"
SW_RESTORE = 9


def settings_path() -> Path:
    local_app_data = os.environ.get("LOCALAPPDATA")
    base = Path(local_app_data) if local_app_data else Path.home() / "AppData" / "Local"
    return base / SETTINGS_DIRECTORY_NAME / SETTINGS_FILE_NAME


def load_settings() -> None:
    """Load valid per-user preferences, leaving defaults for missing/bad values."""
    global timing_preset_name, auto_trigger_window_seconds, focus_wait_seconds, enter_wait_seconds
    global target_process_names, target_application_label
    try:
        data = json.loads(settings_path().read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            return

        preset = data.get("timing_preset")
        if preset in TIMING_PRESETS:
            timing_preset_name = preset

        numeric_settings = (
            ("auto_trigger_window_seconds", 1.0, 120.0),
            ("focus_wait_seconds", 0.0, 30.0),
            ("enter_wait_seconds", 0.0, 60.0),
        )
        for name, minimum, maximum in numeric_settings:
            value = data.get(name)
            if isinstance(value, (int, float)) and not isinstance(value, bool):
                globals()[name] = min(maximum, max(minimum, float(value)))

        label = data.get("target_application_label")
        processes = data.get("target_process_names")
        if (
            isinstance(label, str) and label.strip()
            and isinstance(processes, list) and processes
            and all(isinstance(item, str) and item.strip() for item in processes)
        ):
            target_application_label = label
            target_process_names = {item.lower() for item in processes}
            if target_process_names and target_process_names <= {"vmware.exe", "vmplayer.exe"}:
                target_application_label = VMWARE_TARGET_LABEL
                target_process_names = {"vmware.exe", "vmplayer.exe"}
    except (OSError, UnicodeError, json.JSONDecodeError, TypeError, ValueError):
        pass


def save_settings() -> None:
    """Atomically save the current per-user preferences."""
    destination = settings_path()
    temporary = destination.with_suffix(".tmp")
    data = {
        "version": 1,
        "timing_preset": timing_preset_name,
        "auto_trigger_window_seconds": auto_trigger_window_seconds,
        "focus_wait_seconds": focus_wait_seconds,
        "enter_wait_seconds": enter_wait_seconds,
        "target_application_label": target_application_label,
        "target_process_names": sorted(target_process_names),
    }
    try:
        destination.parent.mkdir(parents=True, exist_ok=True)
        temporary.write_text(
            json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        temporary.replace(destination)
    except OSError as error:
        append_runtime_log(f"保存设置失败：{error}")

SC_LEFT_SHIFT = 0x2A
SC_ENTER = 0x1C
SC_TAB = 0x0F
SC_SPACE = 0x39
VMWARE_VNC_HOST = "127.0.0.1"
VMWARE_VNC_PORT = 5905
VMWARE_VNC_PORT_MAX = 5999


user32 = ctypes.WinDLL("user32", use_last_error=True)
kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)
ENUMWINDOWSPROC = ctypes.WINFUNCTYPE(wintypes.BOOL, wintypes.HWND, wintypes.LPARAM)


class KEYBDINPUT(ctypes.Structure):
    _fields_ = [
        ("wVk", wintypes.WORD),
        ("wScan", wintypes.WORD),
        ("dwFlags", wintypes.DWORD),
        ("time", wintypes.DWORD),
        ("dwExtraInfo", ctypes.c_size_t),
    ]


class MOUSEINPUT(ctypes.Structure):
    _fields_ = [
        ("dx", wintypes.LONG),
        ("dy", wintypes.LONG),
        ("mouseData", wintypes.DWORD),
        ("dwFlags", wintypes.DWORD),
        ("time", wintypes.DWORD),
        ("dwExtraInfo", ctypes.c_size_t),
    ]


class HARDWAREINPUT(ctypes.Structure):
    _fields_ = [
        ("uMsg", wintypes.DWORD),
        ("wParamL", wintypes.WORD),
        ("wParamH", wintypes.WORD),
    ]


class INPUT_UNION(ctypes.Union):
    _fields_ = [
        ("mi", MOUSEINPUT),
        ("ki", KEYBDINPUT),
        ("hi", HARDWAREINPUT),
    ]


class INPUT(ctypes.Structure):
    _anonymous_ = ("union",)
    _fields_ = [("type", wintypes.DWORD), ("union", INPUT_UNION)]


class KBDLLHOOKSTRUCT(ctypes.Structure):
    _fields_ = [
        ("vkCode", wintypes.DWORD),
        ("scanCode", wintypes.DWORD),
        ("flags", wintypes.DWORD),
        ("time", wintypes.DWORD),
        ("dwExtraInfo", ctypes.c_size_t),
    ]


HOOKPROC = ctypes.WINFUNCTYPE(ctypes.c_ssize_t, ctypes.c_int, wintypes.WPARAM, wintypes.LPARAM)


class RAWINPUTDEVICE(ctypes.Structure):
    _fields_ = [
        ("usUsagePage", wintypes.USHORT),
        ("usUsage", wintypes.USHORT),
        ("dwFlags", wintypes.DWORD),
        ("hwndTarget", wintypes.HWND),
    ]


class RAWINPUTHEADER(ctypes.Structure):
    _fields_ = [
        ("dwType", wintypes.DWORD),
        ("dwSize", wintypes.DWORD),
        ("hDevice", wintypes.HANDLE),
        ("wParam", wintypes.WPARAM),
    ]


class RAWKEYBOARD(ctypes.Structure):
    _fields_ = [
        ("MakeCode", wintypes.USHORT),
        ("Flags", wintypes.USHORT),
        ("Reserved", wintypes.USHORT),
        ("VKey", wintypes.USHORT),
        ("Message", wintypes.UINT),
        ("ExtraInformation", wintypes.ULONG),
    ]


user32.SendInput.argtypes = (wintypes.UINT, ctypes.POINTER(INPUT), ctypes.c_int)
user32.SendInput.restype = wintypes.UINT
user32.MapVirtualKeyW.argtypes = (wintypes.UINT, wintypes.UINT)
user32.MapVirtualKeyW.restype = wintypes.UINT
user32.keybd_event.argtypes = (wintypes.BYTE, wintypes.BYTE, wintypes.DWORD, ctypes.c_size_t)
user32.keybd_event.restype = None
user32.GetAsyncKeyState.argtypes = (ctypes.c_int,)
user32.GetAsyncKeyState.restype = ctypes.c_short
user32.GetClipboardSequenceNumber.argtypes = ()
user32.GetClipboardSequenceNumber.restype = wintypes.DWORD
user32.GetForegroundWindow.argtypes = ()
user32.GetForegroundWindow.restype = wintypes.HWND
user32.GetWindowThreadProcessId.argtypes = (wintypes.HWND, ctypes.POINTER(wintypes.DWORD))
user32.GetWindowThreadProcessId.restype = wintypes.DWORD
user32.EnumWindows.argtypes = (ENUMWINDOWSPROC, wintypes.LPARAM)
user32.EnumWindows.restype = wintypes.BOOL
user32.IsWindowVisible.argtypes = (wintypes.HWND,)
user32.IsWindowVisible.restype = wintypes.BOOL
user32.GetWindowTextLengthW.argtypes = (wintypes.HWND,)
user32.GetWindowTextLengthW.restype = ctypes.c_int
user32.GetWindowTextW.argtypes = (wintypes.HWND, wintypes.LPWSTR, ctypes.c_int)
user32.GetWindowTextW.restype = ctypes.c_int
user32.FindWindowW.argtypes = (wintypes.LPCWSTR, wintypes.LPCWSTR)
user32.FindWindowW.restype = wintypes.HWND
user32.ShowWindow.argtypes = (wintypes.HWND, ctypes.c_int)
user32.ShowWindow.restype = wintypes.BOOL
user32.SetForegroundWindow.argtypes = (wintypes.HWND,)
user32.SetForegroundWindow.restype = wintypes.BOOL
user32.MessageBoxW.argtypes = (wintypes.HWND, wintypes.LPCWSTR, wintypes.LPCWSTR, wintypes.UINT)
user32.MessageBoxW.restype = ctypes.c_int
user32.SetWindowsHookExW.argtypes = (ctypes.c_int, HOOKPROC, wintypes.HINSTANCE, wintypes.DWORD)
user32.SetWindowsHookExW.restype = wintypes.HANDLE
user32.CallNextHookEx.argtypes = (wintypes.HANDLE, ctypes.c_int, wintypes.WPARAM, wintypes.LPARAM)
user32.CallNextHookEx.restype = ctypes.c_ssize_t
user32.UnhookWindowsHookEx.argtypes = (wintypes.HANDLE,)
user32.UnhookWindowsHookEx.restype = wintypes.BOOL
user32.PeekMessageW.argtypes = (ctypes.POINTER(wintypes.MSG), wintypes.HWND, wintypes.UINT, wintypes.UINT, wintypes.UINT)
user32.PeekMessageW.restype = wintypes.BOOL
user32.TranslateMessage.argtypes = (ctypes.POINTER(wintypes.MSG),)
user32.TranslateMessage.restype = wintypes.BOOL
user32.DispatchMessageW.argtypes = (ctypes.POINTER(wintypes.MSG),)
user32.DispatchMessageW.restype = ctypes.c_ssize_t
user32.CreateWindowExW.argtypes = (
    wintypes.DWORD, wintypes.LPCWSTR, wintypes.LPCWSTR, wintypes.DWORD,
    ctypes.c_int, ctypes.c_int, ctypes.c_int, ctypes.c_int,
    wintypes.HWND, wintypes.HMENU, wintypes.HINSTANCE, wintypes.LPVOID,
)
user32.CreateWindowExW.restype = wintypes.HWND
user32.DestroyWindow.argtypes = (wintypes.HWND,)
user32.DestroyWindow.restype = wintypes.BOOL
user32.RegisterRawInputDevices.argtypes = (
    ctypes.POINTER(RAWINPUTDEVICE), wintypes.UINT, wintypes.UINT,
)
user32.RegisterRawInputDevices.restype = wintypes.BOOL
user32.GetRawInputData.argtypes = (
    wintypes.HANDLE, wintypes.UINT, wintypes.LPVOID,
    ctypes.POINTER(wintypes.UINT), wintypes.UINT,
)
user32.GetRawInputData.restype = wintypes.UINT
user32.OpenClipboard.argtypes = (wintypes.HWND,)
user32.OpenClipboard.restype = wintypes.BOOL
user32.CloseClipboard.argtypes = ()
user32.CloseClipboard.restype = wintypes.BOOL
user32.GetClipboardData.argtypes = (wintypes.UINT,)
user32.GetClipboardData.restype = wintypes.HANDLE
kernel32.GlobalLock.argtypes = (wintypes.HGLOBAL,)
kernel32.GlobalLock.restype = wintypes.LPVOID
kernel32.GlobalUnlock.argtypes = (wintypes.HGLOBAL,)
kernel32.GlobalUnlock.restype = wintypes.BOOL
kernel32.CreateMutexW.argtypes = (wintypes.LPVOID, wintypes.BOOL, wintypes.LPCWSTR)
kernel32.CreateMutexW.restype = wintypes.HANDLE
kernel32.CloseHandle.argtypes = (wintypes.HANDLE,)
kernel32.CloseHandle.restype = wintypes.BOOL
kernel32.OpenProcess.argtypes = (wintypes.DWORD, wintypes.BOOL, wintypes.DWORD)
kernel32.OpenProcess.restype = wintypes.HANDLE
kernel32.QueryFullProcessImageNameW.argtypes = (
    wintypes.HANDLE, wintypes.DWORD, wintypes.LPWSTR, ctypes.POINTER(wintypes.DWORD),
)
kernel32.QueryFullProcessImageNameW.restype = wintypes.BOOL


def show_error(message: str) -> None:
    user32.MessageBoxW(None, message, "Cloud Hardware Typist", 0x10)


def sleep_ms(milliseconds: int) -> bool:
    """Sleep in short intervals so cancellation responds promptly."""
    deadline = time.monotonic() + milliseconds / 1000
    while True:
        if cancel_event.is_set():
            return False
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            return True
        time.sleep(min(remaining, 0.025))


def random_between(low: int, high: int) -> int:
    return random.randint(low, high)


def timing_range(kind: str) -> tuple[int, int]:
    profile = TIMING_PRESETS[timing_preset_name]
    return profile[kind]


def random_timing(kind: str) -> int:
    low, high = timing_range(kind)
    return random_between(low, high)


def key_is_down(virtual_key: int) -> bool:
    return bool(user32.GetAsyncKeyState(virtual_key) & 0x8000)


def read_unicode_clipboard() -> str | None:
    # Clipboard access can briefly be locked by the app that supplied the copied text.
    for _ in range(40):
        if user32.OpenClipboard(None):
            try:
                handle = user32.GetClipboardData(CF_UNICODETEXT)
                if not handle:
                    return None
                pointer = kernel32.GlobalLock(handle)
                if not pointer:
                    return None
                try:
                    return ctypes.wstring_at(pointer)
                finally:
                    kernel32.GlobalUnlock(handle)
            finally:
                user32.CloseClipboard()
        time.sleep(0.025)
    return None


def make_key_map() -> dict[str, tuple[int, bool]]:
    mapping: dict[str, tuple[int, bool]] = {}

    letters = "abcdefghijklmnopqrstuvwxyz"
    letter_scancodes = [
        0x1E, 0x30, 0x2E, 0x20, 0x12, 0x21, 0x22, 0x23, 0x17,
        0x24, 0x25, 0x26, 0x32, 0x31, 0x18, 0x19, 0x10, 0x13,
        0x1F, 0x14, 0x16, 0x2F, 0x11, 0x2D, 0x15, 0x2C,
    ]
    for character, scancode in zip(letters, letter_scancodes, strict=True):
        mapping[character] = (scancode, False)
        mapping[character.upper()] = (scancode, True)

    digits = "1234567890"
    digit_scancodes = [0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B]
    for character, scancode in zip(digits, digit_scancodes, strict=True):
        mapping[character] = (scancode, False)

    unshifted = ["-", "=", "[", "]", "\\", ";", "'", ",", ".", "/", "`"]
    shifted = ["_", "+", "{", "}", "|", ":", '"', "<", ">", "?", "~"]
    punctuation_scancodes = [0x0C, 0x0D, 0x1A, 0x1B, 0x2B, 0x27, 0x28, 0x33, 0x34, 0x35, 0x29]
    for character, scancode in zip(unshifted, punctuation_scancodes, strict=True):
        mapping[character] = (scancode, False)
    for character, scancode in zip(shifted, punctuation_scancodes, strict=True):
        mapping[character] = (scancode, True)

    mapping["!"] = (0x02, True)
    mapping["@"] = (0x03, True)
    mapping["#"] = (0x04, True)
    mapping["$"] = (0x05, True)
    mapping["%"] = (0x06, True)
    mapping["^"] = (0x07, True)
    mapping["&"] = (0x08, True)
    mapping["*"] = (0x09, True)
    mapping["("] = (0x0A, True)
    mapping[")"] = (0x0B, True)
    return mapping


KEY_MAP = make_key_map()
cancel_event = threading.Event()
shutdown_event = threading.Event()
clipboard_detection_paused = threading.Event()
reset_validity_event = threading.Event()
typing_lock = threading.Lock()
typing_active_event = threading.Event()
status_queue: queue.Queue[str] = queue.Queue()
health_queue: queue.Queue[str] = queue.Queue()
clipboard_preview_queue: queue.Queue[str] = queue.Queue()
clipboard_update_time_queue: queue.Queue[str] = queue.Queue()


def publish_status(message: str) -> None:
    status_queue.put(message)


def append_runtime_log(message: str) -> None:
    base = Path(sys.executable).parent if getattr(sys, "frozen", False) else Path(__file__).parent
    log_path = base / "CloudHardwareTypist.log"
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S")
    with log_path.open("a", encoding="utf-8") as log_file:
        log_file.write(f"[{timestamp}] {message}\n")


class RfbKeyboardClient:
    """Minimal RFB client used only for VMware's loopback VNC keyboard."""

    def __init__(self, host: str, port: int) -> None:
        self.socket = socket.create_connection((host, port), timeout=3.0)
        self.socket.settimeout(3.0)
        try:
            self._handshake()
        except BaseException:
            self.socket.close()
            raise

    def _receive_exactly(self, count: int) -> bytes:
        chunks = bytearray()
        while len(chunks) < count:
            chunk = self.socket.recv(count - len(chunks))
            if not chunk:
                raise ConnectionError("VMware VNC 连接意外关闭")
            chunks.extend(chunk)
        return bytes(chunks)

    def _handshake(self) -> None:
        server_version = self._receive_exactly(12)
        if not server_version.startswith(b"RFB "):
            raise ConnectionError("VMware 返回了无效的 VNC 协议头")
        self.socket.sendall(b"RFB 003.008\n")

        security_count = self._receive_exactly(1)[0]
        if security_count == 0:
            reason_length = struct.unpack("!I", self._receive_exactly(4))[0]
            reason = self._receive_exactly(reason_length).decode("utf-8", "replace")
            raise PermissionError("VMware VNC 拒绝连接：" + reason)
        security_types = self._receive_exactly(security_count)
        if 1 not in security_types:
            raise PermissionError("VMware VNC 未开放仅本机免认证连接")
        self.socket.sendall(b"\x01")
        security_result = struct.unpack("!I", self._receive_exactly(4))[0]
        if security_result != 0:
            raise PermissionError("VMware VNC 安全协商失败")

        # Shared desktop prevents this keyboard-only connection from evicting
        # VMware Workstation's own console session.
        self.socket.sendall(b"\x01")
        server_init = self._receive_exactly(24)
        self.width, self.height = struct.unpack("!HH", server_init[:4])
        name_length = struct.unpack("!I", server_init[20:24])[0]
        if name_length:
            self._receive_exactly(name_length)

    def send_key(self, keysym: int, key_up: bool = False) -> None:
        self.socket.sendall(struct.pack("!BBHI", 4, 0 if key_up else 1, 0, keysym))

    def click(self, x: int, y: int) -> None:
        self.socket.sendall(struct.pack("!BBHH", 5, 1, x, y))
        self.socket.sendall(struct.pack("!BBHH", 5, 0, x, y))

    def close(self) -> None:
        self.socket.close()


VNC_SHIFTED_BASE = dict(zip(
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ_+{}|:\"<>?~!@#$%^&*()",
    "abcdefghijklmnopqrstuvwxyz-=[]\\;',./`1234567890",
    strict=True,
))


def send_vnc_character(client: RfbKeyboardClient, character: str) -> bool:
    keysyms = {"\n": 0xFF0D, "\t": 0xFF09}
    needs_shift = character in VNC_SHIFTED_BASE
    base_character = VNC_SHIFTED_BASE.get(character, character)
    keysym = keysyms.get(base_character, ord(base_character))
    if needs_shift:
        client.send_key(0xFFE1)  # Shift_L
    client.send_key(keysym)
    if not sleep_ms(random_timing("key_down")):
        client.send_key(keysym, key_up=True)
        if needs_shift:
            client.send_key(0xFFE1, key_up=True)
        return False
    client.send_key(keysym, key_up=True)
    if needs_shift:
        client.send_key(0xFFE1, key_up=True)
    return not cancel_event.is_set()


def running_vmware_config_paths() -> list[Path]:
    """Return VMware's registered VMX paths without assuming a fixed library location."""
    paths: list[Path] = []
    try:
        with winreg.OpenKey(
            winreg.HKEY_CURRENT_USER, r"Software\VMware, Inc.\Running VM List"
        ) as key:
            index = 0
            while True:
                try:
                    name, value, _kind = winreg.EnumValue(key, index)
                except OSError:
                    break
                index += 1
                path_text = name if name.lower().endswith(".vmx") else value
                if isinstance(path_text, str) and path_text.lower().endswith(".vmx"):
                    path = Path(path_text)
                    if path.exists() and path not in paths:
                        paths.append(path)
    except OSError:
        pass
    return paths


def vmrun_running_config_paths() -> list[Path]:
    vmrun = find_vmrun()
    if vmrun is None:
        return []
    try:
        result = subprocess.run(
            [str(vmrun), "-T", "ws", "list"],
            capture_output=True, text=True, encoding="utf-8", errors="replace",
            timeout=15, creationflags=subprocess.CREATE_NO_WINDOW,
        )
    except (OSError, subprocess.SubprocessError):
        return []
    return [
        Path(line.strip()) for line in result.stdout.splitlines()
        if line.strip().lower().endswith(".vmx") and Path(line.strip()).is_file()
    ]


def inventory_vmware_config_paths() -> list[Path]:
    inventory = Path(os.environ.get("APPDATA", "")) / "VMware" / "inventory.vmls"
    if not inventory.is_file():
        return []
    try:
        text, _encoding = read_vmx_text(inventory)
    except OSError:
        return []
    paths: list[Path] = []
    for value in re.findall(r'(?im)^vmlist\d+\.config\s*=\s*"([^"]+)"', text):
        path = Path(value)
        if path.is_file() and path not in paths:
            paths.append(path)
    return paths


def discover_vmware_config_paths() -> tuple[list[Path], set[Path]]:
    running = set(vmrun_running_config_paths())
    discovered: list[Path] = []
    for path in (*running, *running_vmware_config_paths(), *inventory_vmware_config_paths()):
        if path.is_file() and path not in discovered:
            discovered.append(path)
    return discovered, running


def scan_vmx_files(
    directory: Path,
    cancel: threading.Event,
    progress: Callable[[int, int], None] | None = None,
) -> list[Path]:
    """Recursively scan off the GUI thread while pruning irrelevant lock/system trees."""
    found: list[Path] = []
    scanned_directories = 0
    last_reported_found = 0
    skipped_names = {"$recycle.bin", "system volume information"}
    for current, directories, files in os.walk(directory, onerror=lambda _error: None):
        if cancel.is_set():
            break
        directories[:] = [
            name for name in directories
            if name.casefold() not in skipped_names
            and not name.casefold().endswith(".lck")
            and ".lck.codex-stale-" not in name.casefold()
        ]
        scanned_directories += 1
        for name in files:
            if name.casefold().endswith(".vmx"):
                found.append(Path(current) / name)
        if progress is not None and (
            scanned_directories % 50 == 0 or len(found) != last_reported_found
        ):
            progress(scanned_directories, len(found))
            last_reported_found = len(found)
    if progress is not None:
        progress(scanned_directories, len(found))
    return sorted(found)


def read_vmx_text(path: Path) -> tuple[str, str]:
    raw = path.read_bytes()
    for encoding in ("utf-8-sig", "gbk"):
        try:
            return raw.decode(encoding), encoding
        except UnicodeDecodeError:
            pass
    return raw.decode("latin-1"), "latin-1"


def vmx_value(text: str, key: str) -> str | None:
    match = re.search(
        rf"(?im)^\s*{re.escape(key)}\s*=\s*\"([^\"]*)\"\s*$", text
    )
    return match.group(1) if match else None


def vmx_is_locked(path: Path) -> bool:
    return (path.parent / (path.name + ".lck")).exists()


def same_windows_path(left: Path, right: Path) -> bool:
    return os.path.normcase(os.path.abspath(left)) == os.path.normcase(os.path.abspath(right))


def vmx_is_running(path: Path) -> bool:
    return any(same_windows_path(path, running) for running in vmrun_running_config_paths())


def archive_stale_vmx_lock(path: Path) -> Path | None:
    """Move a non-active VM's leftover lock aside so it remains recoverable."""
    lock_path = path.parent / (path.name + ".lck")
    if not lock_path.exists():
        return None
    if vmx_is_running(path):
        raise PermissionError("虚拟机仍在运行，不能处理其 VMX 配置锁")
    timestamp = time.strftime("%Y%m%d-%H%M%S")
    archived = path.parent / (lock_path.name + f".codex-stale-{timestamp}")
    suffix = 1
    while archived.exists():
        archived = path.parent / (lock_path.name + f".codex-stale-{timestamp}-{suffix}")
        suffix += 1
    lock_path.replace(archived)
    return archived


def find_vmrun() -> Path | None:
    candidates = (
        Path(os.environ.get("ProgramFiles", r"C:\Program Files"))
        / "VMware" / "VMware Workstation" / "vmrun.exe",
        Path(os.environ.get("ProgramFiles(x86)", r"C:\Program Files (x86)"))
        / "VMware" / "VMware Workstation" / "vmrun.exe",
    )
    return next((path for path in candidates if path.is_file()), None)


def suspend_vmware_vm(path: Path, timeout_seconds: float = 60.0) -> None:
    """Soft-suspend one VM and wait until VMware releases its VMX lock."""
    vmrun = find_vmrun()
    if vmrun is None:
        raise FileNotFoundError("未找到 VMware vmrun.exe")
    startup_info = subprocess.STARTUPINFO()
    startup_info.dwFlags |= subprocess.STARTF_USESHOWWINDOW
    result = subprocess.run(
        [str(vmrun), "-T", "ws", "suspend", str(path), "soft"],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=timeout_seconds,
        startupinfo=startup_info,
        creationflags=subprocess.CREATE_NO_WINDOW,
    )
    if result.returncode != 0:
        detail = (result.stderr or result.stdout).strip()
        raise RuntimeError(detail or f"vmrun 返回错误代码 {result.returncode}")
    deadline = time.monotonic() + timeout_seconds
    while vmx_is_running(path) and time.monotonic() < deadline:
        time.sleep(0.2)
    if vmx_is_running(path):
        raise TimeoutError("挂起已执行，但虚拟机仍出现在 VMware 运行列表中")
    archive_stale_vmx_lock(path)


def configure_vmx_vnc(path: Path, port: int) -> Path:
    """Back up and atomically add/update localhost-only VMware VNC settings."""
    if vmx_is_running(path):
        raise PermissionError("虚拟机仍在运行，请先完成挂起")
    archive_stale_vmx_lock(path)
    text, encoding = read_vmx_text(path)
    settings = {
        "RemoteDisplay.vnc.enabled": "TRUE",
        "RemoteDisplay.vnc.ip": VMWARE_VNC_HOST,
        "RemoteDisplay.vnc.port": str(port),
    }
    for key, value in settings.items():
        pattern = re.compile(rf"(?im)^\s*{re.escape(key)}\s*=.*$")
        replacement = f'{key} = "{value}"'
        text, count = pattern.subn(replacement, text)
        if count == 0:
            text = text.rstrip("\r\n") + "\r\n" + replacement + "\r\n"

    timestamp = time.strftime("%Y%m%d-%H%M%S")
    backup = path.with_name(path.name + f".codex-backup-{timestamp}")
    suffix = 1
    while backup.exists():
        backup = path.with_name(path.name + f".codex-backup-{timestamp}-{suffix}")
        suffix += 1
    backup.write_bytes(path.read_bytes())
    temporary = path.with_name(path.name + ".vnc-config.tmp")
    temporary.write_bytes(text.encode(encoding))
    temporary.replace(path)
    return backup


def vmware_vnc_endpoint() -> tuple[str, int]:
    """Resolve the focused VMware VM's configured port instead of assuming 5905."""
    foreground = user32.GetForegroundWindow()
    title_length = user32.GetWindowTextLengthW(foreground)
    title_buffer = ctypes.create_unicode_buffer(title_length + 1)
    user32.GetWindowTextW(foreground, title_buffer, title_length + 1)
    foreground_title = title_buffer.value.casefold()
    saved_target_label = target_application_label.casefold()
    candidates: list[tuple[str, int, Path]] = []
    running_paths: list[Path] = []
    for path in (*vmrun_running_config_paths(), *running_vmware_config_paths()):
        if path not in running_paths:
            running_paths.append(path)
    for path in running_paths:
        try:
            text, _encoding = read_vmx_text(path)
            if (vmx_value(text, "RemoteDisplay.vnc.enabled") or "").upper() != "TRUE":
                continue
            port = int(vmx_value(text, "RemoteDisplay.vnc.port") or "")
            display_name = (vmx_value(text, "displayName") or path.stem).casefold()
            if VMWARE_VNC_PORT <= port <= VMWARE_VNC_PORT_MAX:
                candidates.append((display_name, port, path))
        except (OSError, UnicodeError, ValueError):
            continue
    foreground_matching = [
        (VMWARE_VNC_HOST, port) for name, port, _path in candidates
        if name in foreground_title
    ]
    if len(foreground_matching) == 1:
        return foreground_matching[0]
    saved_target_matching = [
        (VMWARE_VNC_HOST, port) for name, port, _path in candidates
        if name in saved_target_label
    ]
    if not foreground_matching and len(saved_target_matching) == 1:
        return saved_target_matching[0]
    if len(candidates) == 1:
        return VMWARE_VNC_HOST, candidates[0][1]
    candidate_names = "、".join(name for name, _port, _path in candidates) or "无"
    raise ConnectionError(
        f"无法从当前窗口确定 VMware 虚拟机（运行候选：{candidate_names}），"
        "请在目标应用中选择具体虚拟机窗口"
    )


def send_scan_code(scancode: int, key_up: bool = False) -> None:
    # VMware Workstation reads its console keyboard through a legacy Windows
    # keyboard path on some host configurations and silently discards SendInput
    # scan-code events. keybd_event uses that compatible path. This decision is
    # made per event so releasing Shift remains safe if focus changes mid-run.
    if foreground_process_name() in {"vmware.exe", "vmplayer.exe"}:
        virtual_key = user32.MapVirtualKeyW(scancode, MAPVK_VSC_TO_VK_EX)
        if not virtual_key:
            raise OSError(f"无法把扫描码 0x{scancode:02X} 转换为虚拟键")
        flags = KEYEVENTF_KEYUP if key_up else 0
        user32.keybd_event(virtual_key, scancode, flags, 0)
        return

    flags = KEYEVENTF_SCANCODE | (KEYEVENTF_KEYUP if key_up else 0)
    event = INPUT(type=INPUT_KEYBOARD, ki=KEYBDINPUT(0, scancode, flags, 0, 0))
    sent = user32.SendInput(1, ctypes.byref(event), ctypes.sizeof(INPUT))
    if sent != 1:
        raise ctypes.WinError(ctypes.get_last_error())


def send_physical_key(scancode: int, needs_shift: bool) -> bool:
    """Emit the real key-down/key-up sequence, with a deliberate Shift dwell."""
    if needs_shift:
        send_scan_code(SC_LEFT_SHIFT)
        if not sleep_ms(random_timing("shift")):
            send_scan_code(SC_LEFT_SHIFT, key_up=True)
            return False

    send_scan_code(scancode)
    if not sleep_ms(random_timing("key_down")):
        send_scan_code(scancode, key_up=True)
        if needs_shift:
            send_scan_code(SC_LEFT_SHIFT, key_up=True)
        return False
    send_scan_code(scancode, key_up=True)

    if needs_shift:
        if not sleep_ms(random_timing("shift")):
            send_scan_code(SC_LEFT_SHIFT, key_up=True)
            return False
        send_scan_code(SC_LEFT_SHIFT, key_up=True)
    return not cancel_event.is_set()


def character_pause(character: str) -> int:
    if character == "\n":
        return random_timing("newline")
    if character in " \t":
        return random_timing("space")
    if character in ".,;:!?":
        return random_timing("punctuation")
    return random_timing("character")


def unsupported_characters(text: str) -> list[str]:
    supported_control = {"\r", "\n", "\t", " "}
    unsupported = []
    for character in text:
        if character not in KEY_MAP and character not in supported_control and character not in unsupported:
            unsupported.append(character)
    return unsupported


def is_chinese_character(character: str) -> bool:
    codepoint = ord(character)
    return (
        0x3400 <= codepoint <= 0x4DBF
        or 0x4E00 <= codepoint <= 0x9FFF
        or 0xF900 <= codepoint <= 0xFAFF
    )


def type_clipboard() -> None:
    if not typing_lock.acquire(blocking=False):
        typing_active_event.clear()
        publish_status("输入任务正在运行")
        return
    typing_active_event.set()
    typed_count = 0
    total_count = 0
    final_status = "等待剪贴板更新"
    vnc_client: RfbKeyboardClient | None = None
    try:
        cancel_event.clear()
        text = read_unicode_clipboard()
        if not text:
            final_status = "剪贴板无可输入文本"
            show_error("The clipboard has no Unicode text to type.")
            return

        unsupported = unsupported_characters(text)
        if unsupported:
            preview = " ".join(repr(character) for character in unsupported[:12])
            if any(is_chinese_character(character) for character in unsupported):
                final_status = "不支持按键中文"
                show_error("不支持按键中文。请移除剪贴板中的中文后重试。")
            else:
                final_status = "剪贴板包含不支持的字符"
                show_error(
                    "Typing was not started. This strict hardware mode supports only "
                    "US/ANSI keyboard characters. Unsupported characters: " + preview
                )
            return

        total_count = len(text.replace("\r", ""))
        if foreground_process_name() in {"vmware.exe", "vmplayer.exe"}:
            vnc_host, vnc_port = vmware_vnc_endpoint()
            vnc_client = RfbKeyboardClient(vnc_host, vnc_port)
            publish_status("VMware 虚拟键盘：正在输入 0 / " + str(total_count))
        else:
            publish_status(f"正在输入：0 / {total_count}")
        for character in text:
            if cancel_event.is_set():
                final_status = f"输入已停止：{typed_count} / {total_count}"
                return
            if character == "\r":
                continue
            if vnc_client is not None:
                if not send_vnc_character(vnc_client, character):
                    final_status = f"输入已停止：{typed_count} / {total_count}"
                    return
            elif character == "\n":
                if not send_physical_key(SC_ENTER, False):
                    final_status = f"输入已停止：{typed_count} / {total_count}"
                    return
            elif character == "\t":
                if not send_physical_key(SC_TAB, False):
                    final_status = f"输入已停止：{typed_count} / {total_count}"
                    return
            elif character == " ":
                if not send_physical_key(SC_SPACE, False):
                    final_status = f"输入已停止：{typed_count} / {total_count}"
                    return
            else:
                scancode, needs_shift = KEY_MAP[character]
                if not send_physical_key(scancode, needs_shift):
                    final_status = f"输入已停止：{typed_count} / {total_count}"
                    return

            typed_count += 1
            publish_status(f"正在输入：{typed_count} / {total_count}")
            pause_ms = (
                int(enter_wait_seconds * 1000)
                if character == "\n" and typed_count < total_count
                else character_pause(character)
            )
            if not sleep_ms(pause_ms):
                final_status = f"输入已停止：{typed_count} / {total_count}"
                return
        final_status = f"完成：{typed_count} 字符"
    except Exception as error:
        # Keep runtime failures visible in the main window. A modal MessageBox can
        # be hidden behind the cloud client and make the progress appear frozen.
        final_status = f"硬件按键发送失败：{type(error).__name__}: {error}"
    finally:
        if vnc_client is not None:
            vnc_client.close()
        # Always release Shift if a run is interrupted while it is held.
        try:
            send_scan_code(SC_LEFT_SHIFT, key_up=True)
        except OSError:
            pass
        typing_lock.release()
        typing_active_event.clear()
        publish_status(final_status)


def start_typing_thread() -> None:
    if typing_lock.locked() or typing_active_event.is_set():
        return
    if not target_application_has_focus():
        publish_status("目标窗口未获得焦点，未触发输入")
        return
    # Close the small race between starting the thread and acquiring the lock.
    typing_active_event.set()
    threading.Thread(target=type_clipboard, name="cloud-hardware-typist", daemon=True).start()


def run_keyboard_monitor() -> None:
    first_control_release_at = 0.0
    raw_window = user32.CreateWindowExW(
        0, "STATIC", "CloudHardwareTypistRawInput", 0,
        0, 0, 0, 0, HWND_MESSAGE, None, None, None,
    )
    if not raw_window:
        publish_status(f"Raw Input 窗口创建失败：{ctypes.WinError(ctypes.get_last_error())}")
        return

    keyboard_device = RAWINPUTDEVICE(1, 6, RIDEV_INPUTSINK, raw_window)
    if not user32.RegisterRawInputDevices(
        ctypes.byref(keyboard_device), 1, ctypes.sizeof(RAWINPUTDEVICE)
    ):
        publish_status(f"Raw Input 注册失败：{ctypes.WinError(ctypes.get_last_error())}")
        user32.DestroyWindow(raw_window)


def process_name_for_window(window: int) -> str | None:
    if not window:
        return None
    process_id = wintypes.DWORD(0)
    user32.GetWindowThreadProcessId(window, ctypes.byref(process_id))
    if not process_id.value:
        return None
    process = kernel32.OpenProcess(
        PROCESS_QUERY_LIMITED_INFORMATION, False, process_id.value
    )
    if not process:
        return None
    try:
        capacity = wintypes.DWORD(32768)
        path = ctypes.create_unicode_buffer(capacity.value)
        if not kernel32.QueryFullProcessImageNameW(
            process, 0, path, ctypes.byref(capacity)
        ):
            return None
        return path.value.rsplit("\\", 1)[-1].lower()
    finally:
        kernel32.CloseHandle(process)


def foreground_process_name() -> str | None:
    return process_name_for_window(user32.GetForegroundWindow())


def target_application_has_focus() -> bool:
    foreground_window = user32.GetForegroundWindow()
    if target_window_handle is not None:
        return foreground_window == target_window_handle
    return process_name_for_window(foreground_window) in target_process_names


def visible_applications() -> dict[str, set[str]]:
    application_window_handles.clear()
    applications: dict[str, set[str]] = {
        DEFAULT_TARGET_LABEL: set(DEFAULT_TARGET_PROCESSES),
    }
    internal_titles = {"default ime", "msctfime ui", "dde server window"}
    vmware_main_window: int | None = None

    @ENUMWINDOWSPROC
    def collect_window(window: int, _parameter: int) -> bool:
        nonlocal vmware_main_window
        if not user32.IsWindowVisible(window):
            return True
        title_length = user32.GetWindowTextLengthW(window)
        if title_length <= 0:
            return True
        title_buffer = ctypes.create_unicode_buffer(title_length + 1)
        user32.GetWindowTextW(window, title_buffer, title_length + 1)
        title = title_buffer.value.strip()
        process_name = process_name_for_window(window)
        if not title or not process_name:
            return True
        if process_name in {"cloudhardwaretypist.exe", "pythonw.exe"}:
            return True
        normalized_title = title.casefold()
        if normalized_title in internal_titles or normalized_title.startswith("gdi+ window"):
            return True
        if process_name in {"vmware.exe", "vmplayer.exe"}:
            if vmware_main_window is None or "vmware workstation" in normalized_title:
                vmware_main_window = window
            return True
        label = f"{title}（{process_name}）"
        if label in applications:
            label = f"{title}（{process_name}，窗口 {window}）"
        applications[label] = {process_name}
        application_window_handles[label] = window
        return True

    user32.EnumWindows(collect_window, 0)
    if vmware_main_window is not None:
        applications[VMWARE_TARGET_LABEL] = {"vmware.exe", "vmplayer.exe"}
        application_window_handles[VMWARE_TARGET_LABEL] = vmware_main_window
    return applications


def should_schedule_clipboard_update(
    text_changed: bool,
    typing_active: bool,
    clipboard_text: str | None,
    consumed_text: str | None,
) -> bool:
    """Arm once for genuinely new text; reset is the only same-text rearm."""
    return (
        text_changed
        and not typing_active
        and clipboard_text is not None
        and clipboard_text != consumed_text
    )


def run_automation_monitor() -> None:
    """Watch clipboard/focus and automatically type once per clipboard update."""
    last_clipboard_sequence = user32.GetClipboardSequenceNumber()
    last_clipboard_text = read_unicode_clipboard()
    clipboard_preview_queue.put(last_clipboard_text or "")
    pending_sequence: int | None = None
    consumed_clipboard_text = last_clipboard_text
    pending_since = 0.0
    last_health_update = 0.0
    last_text_check = 0.0

    publish_status("等待剪贴板更新")
    while not shutdown_event.is_set():
        sequence = user32.GetClipboardSequenceNumber()
        now = time.monotonic()
        sequence_changed = sequence != last_clipboard_sequence
        clipboard_text = last_clipboard_text
        if sequence_changed or now - last_text_check >= 0.2:
            clipboard_text = read_unicode_clipboard()
            last_text_check = now
        text_changed = clipboard_text is not None and clipboard_text != last_clipboard_text
        clipboard_updated = sequence_changed or text_changed
        trigger_update = should_schedule_clipboard_update(
            text_changed,
            typing_active_event.is_set(),
            clipboard_text,
            consumed_clipboard_text,
        )
        if clipboard_updated:
            clipboard_update_time_queue.put(time.strftime("%H:%M:%S"))

        if reset_validity_event.is_set():
            reset_validity_event.clear()
            last_clipboard_sequence = sequence
            last_clipboard_text = clipboard_text
            clipboard_preview_queue.put(clipboard_text or "")
            pending_sequence = sequence
            pending_since = now
            publish_status(f"有效期已重置：{auto_trigger_window_seconds:g} 秒")

        if clipboard_detection_paused.is_set():
            if sequence_changed or text_changed:
                clipboard_preview_queue.put(clipboard_text or "")
            last_clipboard_sequence = sequence
            last_clipboard_text = clipboard_text
            pending_sequence = None
            if now - last_health_update >= 0.5:
                foreground = foreground_process_name() or "未知"
                health_queue.put(
                    f"监视：已暂停｜前台：{foreground}"
                )
                last_health_update = now
            time.sleep(0.05)
            continue

        if clipboard_updated:
            last_clipboard_sequence = sequence
            last_clipboard_text = clipboard_text
            clipboard_preview_queue.put(clipboard_text or "")

        if typing_active_event.is_set():
            # Consume clipboard sequence changes produced by VMware Tools while
            # typing, but never turn them into another pending typing task.
            pending_sequence = None
            time.sleep(0.02)
            continue

        if trigger_update:
            pending_sequence = sequence
            pending_since = now
            publish_status(f"已更新：{auto_trigger_window_seconds:g} 秒内切换")

        if now - last_health_update >= 0.5:
            foreground = foreground_process_name() or "未知"
            health_queue.put(
                f"监视：正常｜前台：{foreground}"
            )
            last_health_update = now

        if pending_sequence is not None:
            elapsed = now - pending_since
            if elapsed > auto_trigger_window_seconds:
                pending_sequence = None
                publish_status("已超时，等待剪贴板更新")
            elif target_application_has_focus() and not typing_lock.locked():
                publish_status(f"目标已聚焦，{focus_wait_seconds:g} 秒后输入")
                time.sleep(focus_wait_seconds)
                if target_application_has_focus():
                    pending_sequence = None
                    consumed_clipboard_text = clipboard_text
                    start_typing_thread()
                else:
                    publish_status("目标焦点已离开，继续等待")

        time.sleep(0.02)


def run_automation_monitor_guarded() -> None:
    try:
        append_runtime_log("automation monitor thread starting")
        run_automation_monitor()
        append_runtime_log("automation monitor thread stopped normally")
    except BaseException as error:
        details = "".join(traceback.format_exception(type(error), error, error.__traceback__))
        try:
            append_runtime_log("automation monitor crashed:\n" + details)
        finally:
            publish_status(f"监视线程异常：{type(error).__name__}: {error}")
        return

    publish_status("Raw Input 已就绪：等待连续按两次 Ctrl（F8 备用）")
    message = wintypes.MSG()
    try:
        while not shutdown_event.is_set():
            while user32.PeekMessageW(ctypes.byref(message), None, 0, 0, PM_REMOVE):
                if message.message != WM_INPUT:
                    user32.TranslateMessage(ctypes.byref(message))
                    user32.DispatchMessageW(ctypes.byref(message))
                    continue

                byte_count = wintypes.UINT(0)
                header_size = ctypes.sizeof(RAWINPUTHEADER)
                if user32.GetRawInputData(
                    message.lParam, RID_INPUT, None, ctypes.byref(byte_count), header_size
                ) == 0xFFFFFFFF or byte_count.value < header_size + ctypes.sizeof(RAWKEYBOARD):
                    continue
                buffer = ctypes.create_string_buffer(byte_count.value)
                received = user32.GetRawInputData(
                    message.lParam, RID_INPUT, buffer, ctypes.byref(byte_count), header_size
                )
                if received == 0xFFFFFFFF:
                    continue
                header = RAWINPUTHEADER.from_buffer_copy(buffer.raw[:header_size])
                if header.dwType != RIM_TYPEKEYBOARD:
                    continue
                event = RAWKEYBOARD.from_buffer_copy(
                    buffer.raw[header_size:header_size + ctypes.sizeof(RAWKEYBOARD)]
                )
                key_down = event.Message in (WM_KEYDOWN, WM_SYSKEYDOWN)
                key_up = event.Message in (WM_KEYUP, WM_SYSKEYUP)

                if event.VKey == VK_F8 and key_down:
                    publish_status("Raw Input 检测到 F8；松开后开始输入")
                elif event.VKey == VK_F8 and key_up:
                    publish_status("Raw Input 检测到 F8 松开，正在读取剪贴板…")
                    start_typing_thread()
                elif event.VKey in (VK_CONTROL, VK_LCONTROL, VK_RCONTROL) and key_up:
                    now = time.monotonic()
                    if now - first_control_release_at <= DOUBLE_CTRL_WINDOW_SECONDS:
                        first_control_release_at = 0.0
                        publish_status("Raw Input 检测到第二次 Ctrl，正在读取剪贴板…")
                        start_typing_thread()
                    else:
                        first_control_release_at = now
                        publish_status("Raw Input 检测到第一次 Ctrl；请再按一次")
                elif event.VKey == VK_F9 and key_down:
                    cancel_event.set()
                    publish_status("Raw Input 检测到 F9，正在停止当前输入…")
                elif event.VKey == VK_F10 and key_down:
                    cancel_event.set()
                    shutdown_event.set()

            if first_control_release_at and time.monotonic() - first_control_release_at > DOUBLE_CTRL_WINDOW_SECONDS:
                first_control_release_at = 0.0
                publish_status("Raw Input 已就绪：等待连续按两次 Ctrl（F8 备用）")
            time.sleep(0.01)
    finally:
        user32.DestroyWindow(raw_window)


def run_gui() -> None:
    global timing_preset_name, auto_trigger_window_seconds, focus_wait_seconds, enter_wait_seconds
    global target_process_names, target_application_label, target_window_handle
    root = tk.Tk()
    root.title(WINDOW_TITLE)
    root.geometry("500x620")
    root.resizable(False, False)

    save_after_id: str | None = None

    def schedule_settings_save() -> None:
        nonlocal save_after_id
        if save_after_id is not None:
            root.after_cancel(save_after_id)
        save_after_id = root.after(250, save_settings)

    style = ttk.Style(root)
    try:
        style.theme_use("vista")
    except tk.TclError:
        pass
    style.configure("Title.TLabel", font=("Microsoft YaHei UI", 17, "bold"))
    style.configure("Status.TLabel", font=("Microsoft YaHei UI", 12))
    style.configure("Body.TLabel", font=("Microsoft YaHei UI", 10))
    style.configure("Action.TButton", font=("Microsoft YaHei UI", 10), padding=(16, 8))
    style.configure("Control.TButton", font=("Microsoft YaHei UI", 10), padding=(8, 8))

    container = ttk.Frame(root, padding=(18, 16))
    container.pack(fill="both", expand=True)

    ttk.Label(
        container,
        text="复制文本后，在设定的有效期内切换到目标应用；检测到目标应用获得焦点后自动输入。",
        style="Body.TLabel",
        wraplength=440,
        justify="left",
    ).pack(anchor="w", pady=(0, 10))

    status_frame = ttk.LabelFrame(container, text="当前状态", padding=8, height=68)
    status_frame.pack(fill="x")
    status_frame.pack_propagate(False)
    status_var = tk.StringVar(value="正在启动…")
    ttk.Label(
        status_frame,
        textvariable=status_var,
        style="Status.TLabel",
        wraplength=420,
        justify="left",
    ).pack(fill="both", expand=True)

    health_var = tk.StringVar(value="监视线程：正在启动…")
    ttk.Label(
        container,
        textvariable=health_var,
        style="Body.TLabel",
        wraplength=430,
        justify="left",
    ).pack(anchor="w", pady=(5, 0))

    preview_frame = ttk.LabelFrame(
        container, text="剪贴板内容预览｜上次更新时间：等待更新", padding=6
    )
    preview_frame.pack(fill="x", pady=(8, 0))
    preview_scrollbar = ttk.Scrollbar(preview_frame, orient="vertical")
    preview_scrollbar.pack(side="right", fill="y")
    preview_text = tk.Text(
        preview_frame,
        height=2,
        wrap="word",
        font=("Microsoft YaHei UI", 10),
        relief="flat",
        padx=6,
        pady=4,
        yscrollcommand=preview_scrollbar.set,
    )
    preview_text.pack(side="left", fill="both", expand=True)
    preview_scrollbar.configure(command=preview_text.yview)
    preview_text.configure(state="disabled")

    settings_frame = ttk.LabelFrame(container, text="自动触发设置", padding=10)
    settings_frame.pack(fill="x", pady=(8, 0))

    ttk.Label(settings_frame, text="剪贴板更新后的有效期：", style="Body.TLabel").grid(row=0, column=0, sticky="w")
    trigger_window_var = tk.DoubleVar(value=auto_trigger_window_seconds)
    trigger_value_frame = ttk.Frame(settings_frame)
    trigger_value_frame.grid(row=0, column=1, sticky="w", padx=(6, 0))
    trigger_spinbox = ttk.Spinbox(
        trigger_value_frame, from_=1.0, to=120.0, increment=1.0,
        textvariable=trigger_window_var, width=8,
    )
    trigger_spinbox.pack(side="left")
    ttk.Label(trigger_value_frame, text="秒", style="Body.TLabel").pack(side="left", padx=(4, 0))

    ttk.Label(settings_frame, text="获得焦点后等待：", style="Body.TLabel").grid(row=1, column=0, sticky="w", pady=(3, 0))
    focus_wait_var = tk.DoubleVar(value=focus_wait_seconds)
    focus_value_frame = ttk.Frame(settings_frame)
    focus_value_frame.grid(row=1, column=1, sticky="w", padx=(6, 0), pady=(3, 0))
    focus_spinbox = ttk.Spinbox(
        focus_value_frame, from_=0.0, to=30.0, increment=0.1,
        textvariable=focus_wait_var, width=8,
    )
    focus_spinbox.pack(side="left")
    ttk.Label(focus_value_frame, text="秒", style="Body.TLabel").pack(side="left", padx=(4, 0))

    ttk.Label(settings_frame, text="回车后等待时间：", style="Body.TLabel").grid(row=2, column=0, sticky="w", pady=(3, 0))
    enter_wait_var = tk.DoubleVar(value=enter_wait_seconds)
    enter_value_frame = ttk.Frame(settings_frame)
    enter_value_frame.grid(row=2, column=1, sticky="w", padx=(6, 0), pady=(3, 0))
    enter_spinbox = ttk.Spinbox(
        enter_value_frame, from_=0.0, to=60.0, increment=0.5,
        textvariable=enter_wait_var, width=8,
    )
    enter_spinbox.pack(side="left")
    ttk.Label(enter_value_frame, text="秒", style="Body.TLabel").pack(side="left", padx=(4, 0))

    target_row = ttk.Frame(settings_frame)
    target_row.grid(row=3, column=0, columnspan=3, sticky="ew", pady=(3, 0))
    ttk.Label(target_row, text="目标应用：", style="Body.TLabel").pack(side="left")
    application_map = visible_applications()
    if target_application_label not in application_map:
        application_map[target_application_label] = set(target_process_names)
    application_var = tk.StringVar(value=target_application_label)
    application_combo = ttk.Combobox(
        target_row,
        textvariable=application_var,
        values=list(application_map),
        state="readonly",
        width=43,
    )
    application_combo.pack(side="left", fill="x", expand=True, padx=(6, 0))

    def change_target_application(_event: object | None = None) -> None:
        global target_process_names, target_application_label, target_window_handle
        selected = application_var.get()
        if selected not in application_map:
            return
        target_application_label = selected
        target_process_names = set(application_map[selected])
        target_window_handle = application_window_handles.get(selected)
        schedule_settings_save()
        publish_status(f"目标：{selected.split('（', 1)[0]}")

    def refresh_application_list(_event: object | None = None) -> None:
        nonlocal application_map
        application_map = visible_applications()
        if target_application_label not in application_map:
            application_map[target_application_label] = set(target_process_names)
        application_combo.configure(values=list(application_map))
        matching_label = next(
            (
                label for label, window in application_window_handles.items()
                if window == target_window_handle
            ),
            None,
        ) if target_window_handle is not None else next(
            (
                label for label, process_names in application_map.items()
                if label not in application_window_handles
                and set(process_names) == set(target_process_names)
            ),
            None,
        )
        if matching_label is not None:
            application_var.set(matching_label)
        elif application_var.get() not in application_map:
            application_var.set(DEFAULT_TARGET_LABEL)
            change_target_application()

    application_combo.bind("<<ComboboxSelected>>", change_target_application)
    application_combo.bind("<FocusIn>", refresh_application_list)
    application_combo.bind("<Button-1>", refresh_application_list, add="+")

    def apply_wait_settings(*_args: object) -> None:
        global auto_trigger_window_seconds, focus_wait_seconds, enter_wait_seconds
        try:
            auto_trigger_window_seconds = min(120.0, max(1.0, float(trigger_window_var.get())))
            focus_wait_seconds = min(30.0, max(0.0, float(focus_wait_var.get())))
            enter_wait_seconds = min(60.0, max(0.0, float(enter_wait_var.get())))
        except (tk.TclError, ValueError):
            return
        schedule_settings_save()

    trigger_window_var.trace_add("write", apply_wait_settings)
    focus_wait_var.trace_add("write", apply_wait_settings)
    enter_wait_var.trace_add("write", apply_wait_settings)

    preset_frame = ttk.LabelFrame(container, text="按键间隔预设（每次按键独立随机取值）", padding=10)
    preset_frame.pack(fill="x", pady=(8, 0))
    preset_display_to_key = {
        f"{profile['label']} — {profile['character'][0]}–{profile['character'][1]} ms": key
        for key, profile in TIMING_PRESETS.items()
    }
    initial_preset_display = next(
        display for display, key in preset_display_to_key.items() if key == timing_preset_name
    )
    preset_var = tk.StringVar(value=initial_preset_display)

    def change_preset() -> None:
        global timing_preset_name
        timing_preset_name = preset_display_to_key[preset_var.get()]
        profile = TIMING_PRESETS[timing_preset_name]
        low, high = profile["character"]
        schedule_settings_save()
        publish_status(f"速度：{profile['label']}（{low}–{high} ms）")

    preset_combo = ttk.Combobox(
        preset_frame,
        textvariable=preset_var,
        values=list(preset_display_to_key),
        state="readonly",
        width=30,
    )
    preset_combo.pack(anchor="w")
    preset_combo.bind("<<ComboboxSelected>>", lambda _event: change_preset())

    button_row = ttk.Frame(container)
    button_row.pack(side="bottom")

    def request_cancel() -> None:
        cancel_event.set()
        publish_status("正在停止…")

    def request_close() -> None:
        cancel_event.set()
        save_settings()
        shutdown_event.set()

    def request_reset_validity() -> None:
        clipboard_detection_paused.clear()
        pause_button.configure(text="暂停剪贴板检测")
        reset_validity_event.set()

    def toggle_clipboard_detection() -> None:
        if clipboard_detection_paused.is_set():
            clipboard_detection_paused.clear()
            pause_button.configure(text="暂停剪贴板检测")
            publish_status("检测已恢复，等待更新")
        else:
            clipboard_detection_paused.set()
            pause_button.configure(text="恢复剪贴板检测")
            publish_status("检测已暂停，任务已取消")

    def configure_vmware_vnc() -> None:
        detected, running_paths = discover_vmware_config_paths()
        dialog = tk.Toplevel(root)
        dialog.title("配置 VMware VNC")
        dialog.geometry("820x430")
        dialog.minsize(700, 360)
        dialog.transient(root)
        dialog.grab_set()
        scan_cancel = threading.Event()

        def close_dialog() -> None:
            scan_cancel.set()
            dialog.destroy()

        dialog.protocol("WM_DELETE_WINDOW", close_dialog)

        ttk.Label(
            dialog,
            text=(
                "已自动扫描当前运行的虚拟机和 VMware 本地库存。"
                "可选择一项或多项；运行中的虚拟机会在确认后先完整挂起。"
            ),
            wraplength=770,
        ).pack(anchor="w", padx=14, pady=(14, 8))

        tree_frame = ttk.Frame(dialog)
        tree_frame.pack(fill="both", expand=True, padx=14)
        tree = ttk.Treeview(
            tree_frame, columns=("status", "config", "folder"), show="headings",
            selectmode="extended",
        )
        tree.heading("status", text="状态")
        tree.heading("config", text="配置文件")
        tree.heading("folder", text="文件夹路径")
        tree.column("status", width=125, stretch=False)
        tree.column("config", width=190, stretch=False)
        tree.column("folder", width=440)
        scrollbar = ttk.Scrollbar(tree_frame, orient="vertical", command=tree.yview)
        tree.configure(yscrollcommand=scrollbar.set)
        tree.pack(side="left", fill="both", expand=True)
        scrollbar.pack(side="right", fill="y")
        item_paths: dict[str, Path] = {}

        empty_var = tk.StringVar(value="")
        ttk.Label(dialog, textvariable=empty_var).pack(anchor="w", padx=14, pady=(6, 0))

        def add_paths(paths: list[Path], running: set[Path] | None = None) -> None:
            running = running or set()
            known = set(item_paths.values())
            for path in paths:
                if path in known or not path.is_file():
                    continue
                is_running = path in running
                status = "运行中（将挂起）" if is_running else "未运行（可配置）"
                item = tree.insert("", "end", values=(status, path.name, str(path.parent)))
                item_paths[item] = path
                known.add(path)
            children = tree.get_children()
            if children:
                tree.selection_set(children)
                empty_var.set(f"共找到 {len(children)} 个虚拟机配置；可按 Ctrl/Shift 调整选择。")
            else:
                empty_var.set("自动扫描未找到可用的 .vmx，请点击“选择文件夹”。")

        add_paths(detected, running_paths)

        button_frame = ttk.Frame(dialog)
        button_frame.pack(fill="x", padx=14, pady=14)
        apply_button_text = tk.StringVar(value="确认配置所选项")

        def update_apply_button_text(_event: object | None = None) -> None:
            selected = tree.selection()
            has_running = any(
                tree.set(item, "status").startswith("运行中")
                for item in selected if item in item_paths
            )
            apply_button_text.set(
                "确认挂起并配置所选项" if has_running else "确认配置所选项"
            )

        tree.bind("<<TreeviewSelect>>", update_apply_button_text)
        update_apply_button_text()

        def choose_folder() -> None:
            directory = filedialog.askdirectory(
                title="选择包含一个或多个 VMware 虚拟机的文件夹", parent=dialog
            )
            if not directory:
                return
            scan_cancel.clear()
            scan_events: queue.Queue[tuple[object, ...]] = queue.Queue()
            apply_button.configure(state="disabled")
            folder_button.configure(state="disabled")
            empty_var.set(f"正在后台扫描 {directory} …")

            def report_progress(scanned_count: int, found_count: int) -> None:
                scan_events.put(("progress", scanned_count, found_count))

            def scan_worker() -> None:
                scanned = scan_vmx_files(Path(directory), scan_cancel, report_progress)
                scan_events.put(("done", scanned))

            def poll_scan() -> None:
                latest_progress: tuple[object, ...] | None = None
                try:
                    while True:
                        event = scan_events.get_nowait()
                        if event[0] == "progress":
                            latest_progress = event
                        elif event[0] == "done":
                            scanned = list(event[1])
                            apply_button.configure(state="normal")
                            folder_button.configure(state="normal")
                            if not scanned:
                                empty_var.set(f"扫描完成：未在 {directory} 中找到 .vmx 文件。")
                            else:
                                add_paths(scanned, set(vmrun_running_config_paths()))
                            return
                except queue.Empty:
                    pass
                if latest_progress is not None:
                    empty_var.set(
                        f"正在后台扫描 {directory}：已检查 {latest_progress[1]} 个目录，"
                        f"找到 {latest_progress[2]} 个配置…"
                    )
                if dialog.winfo_exists():
                    dialog.after(100, poll_scan)

            threading.Thread(target=scan_worker, name="vmx-folder-scan", daemon=True).start()
            dialog.after(100, poll_scan)

        def apply_selected() -> None:
            selected = list(tree.selection())
            if not selected:
                messagebox.showwarning("未选择", "请先选择至少一个虚拟机。", parent=dialog)
                return
            paths = [item_paths[item] for item in selected]
            current_running = set(vmrun_running_config_paths())
            running_selected = [path for path in paths if path in current_running]
            if running_selected:
                locked_names = "\n".join(f"• {path}" for path in running_selected)
                if not messagebox.askyesno(
                    "确认完整挂起并配置",
                    "将软挂起以下运行中的虚拟机：\n\n" + locked_names
                    + "\n\n挂起完成后备份并修改 VMX；配置后不会自动恢复。是否继续？",
                    parent=dialog,
                ):
                    return

            apply_button.configure(state="disabled")
            folder_button.configure(state="disabled")
            close_button.configure(state="disabled")
            tree.configure(selectmode="none")
            dialog.protocol("WM_DELETE_WINDOW", lambda: None)
            progress_queue: queue.Queue[tuple[object, ...]] = queue.Queue()

            def worker() -> None:
                configured: list[str] = []
                failed: list[str] = []
                failed_paths: set[Path] = set()
                for path in running_selected:
                    progress_queue.put(("progress", f"正在完整挂起：{path.name}…"))
                    try:
                        suspend_vmware_vm(path)
                    except (OSError, RuntimeError, subprocess.SubprocessError) as error:
                        failed.append(f"{path}: 自动挂起失败：{error}")
                        failed_paths.add(path)

                used_ports: set[int] = set()
                for path in paths:
                    if path in failed_paths:
                        continue
                    progress_queue.put(("progress", f"正在备份并配置：{path.name}…"))
                    try:
                        text, _encoding = read_vmx_text(path)
                        existing_text = vmx_value(text, "RemoteDisplay.vnc.port")
                        existing = int(existing_text) if existing_text else None
                        port = existing if existing and VMWARE_VNC_PORT <= existing <= VMWARE_VNC_PORT_MAX else None
                        if port is None or port in used_ports:
                            port = next(candidate for candidate in range(
                                VMWARE_VNC_PORT, VMWARE_VNC_PORT_MAX + 1
                            ) if candidate not in used_ports)
                        backup = configure_vmx_vnc(path, port)
                        used_ports.add(port)
                        configured.append(f"{path.name} → 127.0.0.1:{port}\n  备份：{backup.name}")
                    except (OSError, UnicodeError, ValueError, StopIteration) as error:
                        failed.append(f"{path}: {error}")
                progress_queue.put(("done", configured, failed))

            def poll_worker() -> None:
                try:
                    while True:
                        event = progress_queue.get_nowait()
                        if event[0] == "progress":
                            empty_var.set(str(event[1]))
                        elif event[0] == "done":
                            configured = list(event[1])
                            failed = list(event[2])
                            summary = ""
                            if configured:
                                summary = "配置成功：\n" + "\n".join(configured)
                            if failed:
                                summary += ("\n\n" if summary else "") + "未配置：\n" + "\n".join(failed)
                            if configured:
                                summary += "\n\n请启动或恢复虚拟机，使 VNC 配置生效。"
                            messagebox.showinfo("VMware VNC 配置结果", summary, parent=dialog)
                            if configured:
                                dialog.destroy()
                            else:
                                apply_button.configure(state="normal")
                                folder_button.configure(state="normal")
                                close_button.configure(state="normal")
                                tree.configure(selectmode="extended")
                                dialog.protocol("WM_DELETE_WINDOW", close_dialog)
                            return
                except queue.Empty:
                    pass
                if dialog.winfo_exists():
                    dialog.after(100, poll_worker)

            threading.Thread(target=worker, name="vmware-vnc-config", daemon=True).start()
            dialog.after(100, poll_worker)

        apply_button = ttk.Button(
            button_frame, textvariable=apply_button_text, command=apply_selected,
            style="Action.TButton",
        )
        apply_button.pack(side="left")
        folder_button = ttk.Button(
            button_frame, text="选择文件夹", command=choose_folder,
            style="Action.TButton",
        )
        folder_button.pack(side="left", padx=(10, 0))
        close_button = ttk.Button(button_frame, text="关闭", command=close_dialog)
        close_button.pack(side="right")

    ttk.Button(
        button_row, text="停止当前输入", command=request_cancel,
        style="Control.TButton", width=14,
    ).grid(row=0, column=0, padx=(0, 6))
    ttk.Button(
        button_row, text="重置有效期", command=request_reset_validity,
        style="Control.TButton", width=14,
    ).grid(row=0, column=1, padx=6)
    pause_button = ttk.Button(
        button_row, text="暂停剪贴板检测", command=toggle_clipboard_detection,
        style="Control.TButton", width=16,
    )
    pause_button.grid(row=0, column=2, padx=(6, 0))
    ttk.Button(
        button_row, text="一键配置 VMware VNC", command=configure_vmware_vnc,
        style="Control.TButton", width=24,
    ).grid(row=1, column=0, columnspan=3, pady=(8, 0))

    root.protocol("WM_DELETE_WINDOW", request_close)

    monitor_thread = threading.Thread(
        target=run_automation_monitor_guarded, name="automation-monitor", daemon=True
    )
    monitor_thread.start()

    def refresh_gui() -> None:
        try:
            while True:
                status_var.set(status_queue.get_nowait())
        except queue.Empty:
            pass
        try:
            while True:
                health_var.set(health_queue.get_nowait())
        except queue.Empty:
            pass
        try:
            latest_preview = None
            while True:
                latest_preview = clipboard_preview_queue.get_nowait()
        except queue.Empty:
            if latest_preview is not None:
                display_preview = latest_preview
                if len(display_preview) > 4000:
                    display_preview = display_preview[:4000] + "\n…（预览已截断）"
                preview_text.configure(state="normal")
                preview_text.delete("1.0", "end")
                preview_text.insert("1.0", display_preview or "（剪贴板中没有文本）")
                preview_text.configure(state="disabled")
        try:
            latest_update_time = None
            while True:
                latest_update_time = clipboard_update_time_queue.get_nowait()
        except queue.Empty:
            if latest_update_time is not None:
                preview_frame.configure(
                    text=f"剪贴板内容预览｜上次更新时间：{latest_update_time}"
                )
        if shutdown_event.is_set():
            save_settings()
            root.destroy()
            return
        root.after(50, refresh_gui)

    root.update_idletasks()
    x_position = max(0, (root.winfo_screenwidth() - root.winfo_width()) // 2)
    y_position = max(0, (root.winfo_screenheight() - root.winfo_height()) // 3)
    root.geometry(f"+{x_position}+{y_position}")
    root.after(50, refresh_gui)
    root.mainloop()
    cancel_event.set()
    shutdown_event.set()


def main() -> None:
    load_settings()
    ctypes.set_last_error(0)
    mutex_handle = kernel32.CreateMutexW(None, False, MUTEX_NAME)
    if not mutex_handle:
        show_error(f"Could not create the single-instance guard: {ctypes.WinError(ctypes.get_last_error())}")
        return

    if ctypes.get_last_error() == ERROR_ALREADY_EXISTS:
        existing_window = user32.FindWindowW(None, WINDOW_TITLE)
        if existing_window:
            user32.ShowWindow(existing_window, SW_RESTORE)
            user32.SetForegroundWindow(existing_window)
        kernel32.CloseHandle(mutex_handle)
        return

    try:
        run_gui()
    finally:
        kernel32.CloseHandle(mutex_handle)


if __name__ == "__main__":
    main()
